name = input("Введите ваше имя: ")
familyname = input("Введите вашу фамилию: ")
age = input("Введите ваш возраст: ")
colour = input("Ваш любимый цвет: ")
number = input("Ваше любимое число: ")
print(name)
print(familyname)
print(age)
print(colour)
print(number)
